# The number of items to show in the list of items to select.
# Useful to limit if your terminal is small, as it can be quite buggy if the list doesn't fit.
# Default to 5 if not specified.
items_shown: 5
plex:
    url: https://192.168.0.203:32400
    token: KBYD8RnZV3UymowHq7rc
overseerr:
    url: http://192.168.0.203:5000
    api_key: c636c4acb1b048b88a4e81ee6f82005d
tautulli:
    url: https://YOUR_TAUTULLI_URL
    api_key: YOUR_API_KEY
sonarr: # If you don't use Sonarr, just leave this section out
    url: https://YOUR_SONARR_URL
    api_key: YOUR_API_KEY
sonarr_4k: # If you don't have a 4k Sonarr instance, just leave this section out
    url: https://YOUR_SONARR_4K_URL
    api_key: YOUR_API_KEY
radarr: # If you don't use Radarr, just leave this section out
    url: https://YOUR_RADARR_URL
    api_key: YOUR_API_KEY
radarr_4k: # If you don't have a 4k Radarr instance, just leave this section out
    url: https://YOUR_RADARR_4K_URL
    api_key: YOUR_API_KEY